### ISSUE TITLE
Make it easy to open the project and run it in Android Studio

### ISSUE THREAD

**Issue by daj** [johanley/date4j#1]
The project structure doesn't match the Android Studio defaults, which means the source code doesn't get compiled, and you can't run tests.  This is a shame.  :-(  If you are committed to the current project structure then maybe we need a build.gradle to customize the expected locations?

**Comment by johanley** [comment]
The source tree should be left alone. If the tool doesn't grok the code, then the tool should be configured to do so. 

If you want to create and post a build.gradle file that others could use, then that would be a worthwhile contribution. I'm sure others would be grateful for it. What do you say?

**Comment by daj** [comment]
Unfortunately I'm not going to have time to do this myself any time soon, so happy for you to close the issue.  On a related note, I would suggest adding step by step instructions to the README file to say how to compile the code and run the tests.  If I had know how to do that I would have tried to write a test for the scenario I raised in the other issue (rather than writing the test in my own codebase).
