### ISSUE TITLE
Unexpected results when using the minus method with DayOverflow

### ISSUE THREAD

**Issue by daj** [johanley/date4j#2]
After carefully reading the [API docs for DayOverflow](http://www.date4j.net/javadoc/hirondelle/date4j/DateTime.html#minus%28java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, hirondelle.date4j.DateTime.DayOverflow%29) and [API docs for DayOverflow](http://www.date4j.net/javadoc/hirondelle/date4j/DateTime.DayOverflow.html), we encountered some unexpected behavior.

Scenario:
- Create a DateTime.
- Use the `minus` method to subtract 6 months, with `DateTime.DayOverflow.FirstDay`.
- For some days of the year, this causes an unexpected result, e.g. for 2015-08-31 this selects 2015-01-01, whereas I would expect it to return 2015-02-01.

Here's an example test calculating all the dates in 2015 which hit this unexpected scenario:

```
     public void testGetDateSixMonthsBefore() throws Exception {
        DateTime fakeDate = DateTime.forDateOnly(2015, 1, 1);

        int count = 365;

        while (count > 0) {
            DateTime sixMonthsEarlier = fakeDate.minus(0, 6, 0, 0, 0, 0, 0, DateTime.DayOverflow.FirstDay);

            int days = sixMonthsEarlier.numDaysFrom(fakeDate);

            if (days > 184) {
                String s = fakeDate.format("YYYY-MM-DD") + " goes back " + days + " days";
                Log.w("", s);
            }

            fakeDate = fakeDate.plusDays(1);
            count--;
        }
     }
```

Example output:

```
W/: 2015-03-31 goes back 242 days
W/: 2015-05-31 goes back 242 days
W/: 2015-08-29 goes back 240 days
W/: 2015-08-30 goes back 241 days
W/: 2015-08-31 goes back 242 days
W/: 2015-10-31 goes back 244 days
W/: 2015-12-31 goes back 244 days
```

This issue caused a major production bug for us, as it resulted in our client sending an invalid date range to our server APIs, so a major feature completely stopped working.  We didn't catch it during testing as we developed and tested between 31st May and 29th August.  :-(

The `minusDays` method does not hit any similar issue, presumably because it only ever adjusts the date to valid days.

**Comment by johanley** [comment]
Here's a second test harness, showing the behavior for all overflow styles, for a specific date (2015-03-31).

``` java
import hirondelle.date4j.DateTime;
import hirondelle.date4j.DateTime.DayOverflow;

public class Main {
  /**
   * Calculate 6 months previous to 2015-03-31.
   * The 'base' date is invalid: 2014-09-31 (Sep 31).
   * 
   * Gives this result:
   * LastDay: 2014-09-30 (correct)
   * FirstDay: 2014-08-01 (incorrect, should be 2014-10-01)
   * Spillover: 2014-08-01 (incorrect, should be 2014-10-01)
   */
  public static void main(String... args){
    DateTime test = new DateTime("2015-03-31");
    DayOverflow style = DayOverflow.Spillover;
    DateTime minus6months = test.minus(0,6,0,0,0,0,0,style);
    System.out.println("Style: " + style);
    System.out.println("Minus 6 months: " + minus6months);
    Integer days = minus6months.numDaysFrom(test);
    System.out.println("Num days diff: " + days);
  }
}
```

For the record, here is the output of the above:

Style: LastDay
Minus 6 months: 2014-09-30 00:00:00.000000000
Num days diff: 182

Style: FirstDay
Minus 6 months: 2014-08-01 00:00:00.000000000
Num days diff: 242

Style: Spillover
Minus 6 months: 2014-08-01 00:00:00.000000000
Num days diff: 242

**Comment by johanley** [comment]
I will look at the code tomorrow, and apply a fix as soon as I can. 

The javadoc for DayOverflow.FirstDay states that it refers to the first day of the _next_ month. The idea is that the various overflow styles select a date _near_ the end of the month. From that point of view, coercing Feb 30 to be Feb 1 is inappropriate, since it's not 'nearby' the nominal date.

**Comment by johanley** [comment]
I applied a fix to the master branch today. Thank you for the report. Sorry about the bug.

**Comment by daj** [comment]
Thanks for the quick turnaround!  Our hot fix was to remove calls to this method completely, so we aren't planning to take the updated code any time soon.  I was mostly reporting it to be a good citizen in case this hit anybody else.  :-)  Thanks!
