### ISSUE TITLE
The .format() is really expensive on Android devices

### ISSUE THREAD

**Issue by EsteveAguilera** [johanley/date4j#3]
I've used date4j on a project because this project uses the [CalDroid](https://github.com/roomorama/Caldroid) library by @roomorama, and I've seen that this line of code:

`return dateTime.format("YYYY-MM-DD");`

takes about 6ms to complete!

Now I'm using:

`        String year = String.valueOf(dateTime.getYear());

```
    int monthInt = dateTime.getMonth();
    String monthString = String.valueOf(monthInt);
    if (monthInt < 10) {
        monthString = "0" + monthString;
    }

    int dayInt = dateTime.getDay();
    String dayString = String.valueOf(dayInt);
    if (dayInt < 10) {
        dayString = "0" + dayString;
    }

    return year + "-" + monthString + "-" + dayString;`
```

which takes 0ms...

On a laptop there's almost no difference between the two options...

**Comment by johanley** [comment]
Can you describe what tool you used to measure the execution time?

**Comment by EsteveAguilera** [comment]
I've used the [Hugo library by Jake Wharton](https://github.com/JakeWharton/hugo) to detect the issue.

I've also created an Android app just to test 100 times the same code:
`
        start = System.currentTimeMillis();

```
    for (int i = 0; i<ITERATIONS; i++){
        String year = String.valueOf(dateTime.getYear());

        int monthInt = dateTime.getMonth();
        String monthString = String.valueOf(monthInt);
        if (monthInt < 10) {
            monthString = "0" + monthString;
        }

        int dayInt = dateTime.getDay();
        String dayString = String.valueOf(dayInt);
        if (dayInt < 10) {
            dayString = "0" + dayString;
        }

        resultPlus = year + "-" + monthString + "-" + dayString;
    }

    elapsedTime = System.currentTimeMillis() - start;

    resultPlus = "Elapsed time +: " + elapsedTime + "ms - final output " + resultPlus;

    start = System.currentTimeMillis();

    for (int i = 0; i<ITERATIONS; i++){
        resultParse = dateTime.format("YYYY-MM-DD");
    }

    elapsedTime = System.currentTimeMillis() - start;

    resultFormat = "Elapsed time format: " + elapsedTime + "ms - final output " + resultParse;`
```

dateTime.format() -> **589ms**

Generating the String getting the year, month and day as int and using + to concatenate -> **48ms**

**Comment by johanley** [comment]
I don't think I'm going to address the issue. Sorry.

Date4j's main design goal is clarity and simplicity. It's not performance.
In some cases, it outperforms other tools, in some cases it's just the
opposite.

As a side note: in Java/Android, using nanos as opposed to msecs is
preferred for timings. The precision of msecs is quite poor on many
devices, on the order of +/-10ms. You will get much better precision with
nanos.

Ref:
http://www.javapractices.com/topic/TopicAction.do?Id=85
http://developer.android.com/reference/java/lang/System.html#nanoTime%28%29
- John O'Hanley

**Comment by EsteveAguilera** [comment]
Ok, thanks! 

Feel free to close the issue.
