### ISSUE TITLE
comparing 2 dates

### ISSUE THREAD

**Issue by aimiliano** [johanley/date4j#4]
I would like to point out an issue that might not be an issue after all but let me take you through my example..

i want to compare a date to another date without the  hours , minutes ,seconds etc.

the one date is now without the hh mm ss

```
  //Now Date
        DateTime now = DateTime.now(TimeZone.getDefault()).getStartOfDay();
```

so the other date comes from a feed where the format is "YYYY-MM-DD"

so i  create the date from this format
DateTime date_to_compare = new DateTime(date_strStartDate);

if the date_to_compare is the same day as today,

it doesn't equal the now date.

because date_to_compare has null values for hours, minutes,seconds etc.

so in the end  this never returns true even though its the same date.

```
if (now .gteq(date_to_compare ) && now .lteq(date_to_compare )   ){
   return true;
}
```

in order for this to work i came down to this idea.
DateTime date_to_compare = new DateTime(date_strStartDate+" 00:00:00.0000");
i explicitely add hours minutes, seconds to the date string in order to give the constructor some values.
then the previous statement returns true finally.

but this got me headache for 4 days to understand. i am making this an issue so if you would like to address it as a solution to change the 

default null values of the constructor to zeros  00:00:00.0000.

**Comment by johanley** [comment]
Hi, 
In this case, you should use the 'isSameDayAs' method:

http://www.date4j.net/javadoc/hirondelle/date4j/DateTime.html#isSameDayAs%28hirondelle.date4j.DateTime%29
- John

**Comment by aimiliano** [comment]
Oh ok thank you then i haven't checked out this one!
I am closing this issue leave it here if someone stubmles upon the same question
